branch-defaults:
  master:
    environment: prod
    group_suffix: null
global:
  application_name: chainrenter
  branch: null
  default_ec2_keyname: aws-eb-chainrenter
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
